name: test

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.15
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.15"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest hatchi/tests

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world! :wave:
